### ISSUE TITLE
Runtime Issues

### ISSUE THREAD

**Issue by zhangxq9944** [INK-USC/TriggerNER#15]
Run directly after downloading the code ，error in the picture has occurred ,how can it be solved? 
Thank you very munch.
 python naive.py 运行代码时出现了图片中的问题，求助大佬解决，在此非常感谢。

![image](https://user-images.githubusercontent.com/65837935/123262261-42251000-d52a-11eb-8d6f-b706fe34f314.png)

**Comment by yuchenlin** [comment]
Thanks for the report. @danny911kr would u plz take a look at this? looks like an error cased by empty data...

**Comment by danny911kr** [comment]
@zhangxq9944 Thanks for the report.
Seems the version of overrides cause the issue.
Just update the `requirements.txt` (1bf3572f852cf9aa1f48793f21eeee2ce74f90f0)
Please re-install packages! Thanks a lot!

**Comment by zhangxq9944** [comment]
This question is true,“ overrides == 2.0”
非常感谢！
