### ISSUE TITLE
A question about trigger_list

### ISSUE THREAD

**Issue by 1120161807** [INK-USC/TriggerNER#16]
Hello！Thanks for your code！But I still have a question about the ```trigger_list```, in soft_matcher.py, 140 lines.
 ```trigger_list.extend([" ".join(self.config.idx2word[index] for index in indices if index != 0) for indices in word_seq])```
```word_seq``` represents the positions of triggers in each sentence.(i.e. It will always smaller than ```seq_len```). In that case, ```trigger_list``` will only includes the triggers in the first several sentences, which may be a error.
Did I get it wrong, I wonder?
Thanks for your code again！

**Comment by danny911kr** [comment]
Hi, @1120161807 Thank you for reporting the bug!
Yes, I just fixed it. Thank you for your contribution!
