### ISSUE TITLE
if i use my own chinese corpus , how to design and create my own trigger txt?

### ISSUE THREAD

**Issue by marcusau** [INK-USC/TriggerNER#4]
Thanks a lot.

your method is amazing.

How to  design and create my own trigger txt file if i wanna use my own set of Chinese corpus?

**Comment by danny911kr** [comment]
Hi, Thank you for your interest.

Please refer to our dataset file. (trigger_turk.txt)
and also please refer to #2 .

First, you should split the current corpus into single-entity sentences.
For example,

"Paris is the president of USC" 
-> ['B-PER', 'O', 'O', 'O', 'O', 'O']
-> ['O', 'O', 'O', 'O', 'O', 'B-LOC']

then please annotate triggers on to it.

"Paris is the president of USC" 
-> ['B-PER', 'T-0', 'T-0', 'T-0', 'O', 'O']
-> ['O', 'O', 'O', 'T-0', 'T-0', 'B-LOC']
