### ISSUE TITLE
Environment error

### ISSUE THREAD

**Issue by pengzhaofan** [INK-USC/TriggerNER#5]
![image](https://user-images.githubusercontent.com/20312161/85264167-e2bd9b80-b4a2-11ea-929d-7a43330318a0.png)
Hello, may I ask why this problem is caused？

**Comment by danny911kr** [comment]
Hi, I think it's CUDA environment error.
I haven't seen this before.

Could you try running on CPU to check whether it is CUDA environment error or not?

**Comment by danny911kr** [comment]
I'll close the issue. if you have other issues, pls let me know. Thanks!
