### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by fst813** [INK-USC/TriggerNER#6]
hello!
In the soft_matcher.py file, the index on line 140 should be the position of the trigger. If you convert the position information to Word (using IDx2Word [index]), this seems to be an error.What does trigger_list stand for?

**Comment by danny911kr** [comment]
Hi @fst813 

Sorry for the late reply.
This is not an error. `trigger_list` stands for the string name of the trigger. (`logits_list` stands for trigger vectors, `predicted_list` stands for types of the trigger vectors)

The reason why we use the `trigger_list` is to find the type duplication of the same trigger.
If you look at line 101 at `semi_supervised.py`, you can check the function remove_duplicates.
We are trying to polish the triggers by deleting triggers that have more than one entity type and pooling the multiple trigger vectors of the same trigger.

We will improve the comments around this line.
Thank you for your comments.
