### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wjczf123** [INK-USC/TriggerNER#7]
Hi,
  I think your code may have some problems about data split and model:
  1. In line 101 of semi_supervised.py, 0.2 may be means percentage? I think you should use args.percentage.
  2. In supervised.py, there is no code about data split. Percentage doesn't work at there. 
  3. In your paper, you use CNN-BiLSTM model. But your code use BiLSTM as char-level model.
  I hope you can check it. Thank you a lot for your code.

**Comment by wjczf123** [comment]
I use command: python supervised.py --device cuda:0 --dataset CONLL --percentage 3. The result is 85.56. I think the bug should mainly focus on the data (training data is not 3%).

**Comment by wjczf123** [comment]
naive.py is normal. supervised.py and semi_supervised.py have problem.

**Comment by wjczf123** [comment]
Hope you can fix it as soon as possible.

**Comment by danny911kr** [comment]
Hi @wjczf123,

Sorry for the late reply. 

Thanks for pointing it out. We will add a new argument `--unlabeled_percentage` for controlling the percentage of the unlabeled data we used for semi-supervised training. We will add a new script to generate the splits and the use of the `--percentage` argument to load the respective data split for both `supervised.py` and `semi-supervised.py`, by the end of this week.

Yeah, it is indeed the BiLSTM model for char-modeling, we will update the description in the paper.  (We also tried CNN before, it performed slightly worse. )

Thanks again.

**Comment by wjczf123** [comment]
OK. Thank you.

**Comment by wjczf123** [comment]
Hope you can fix it as soon as possible.

**Comment by danny911kr** [comment]
Hi @wjczf123,

I apologize for the late reply due to other project deadlines.

We just updated the repo.
Thank you for your suggestion.

Here are the tips for running the code

- The dataset we used for `supervised.py` and `semi_supervised.py` is 20% of original training data with triggers. 
   (Sentences are split into a single-entity sentence, and each single-entity sentence has triggers)
- If you run `python supervised.py --device cuda:0 --dataset CONLL --percentage 3`, it means you will use 3% of such trigger dataset. (It should be 0.8% of the training dataset)
- To enable 3% of the original training dataset, you should use `--percentage 15`

**Comment by wjczf123** [comment]
I run your new code. It seems that percentage doesn't work in supervised.py. 
I run: python supervised.py --device cuda:0 --dataset CONLL --percentage 15, test result F1 is 78.73.
I run: python supervised.py --device cuda:1 --dataset CONLL --percentage 3, test result F1 is 86.18.

**Comment by wjczf123** [comment]
I run your new code. It seems that percentage also doesn't work in semi_supervised.py.
I run: python semi_supervised.py --device cuda:0 --dataset CONLL --percentage 20, test result F1 is 85.58.
I run: python semi_supervised.py --device cuda:1 --dataset CONLL --percentage 3, test result F1 is 86.39.

**Comment by wjczf123** [comment]
And what is the setting of argument --unlabeled_percentage? 
Can we reproduce your experiment with the default settings(unlabeled_percentage = 0.8)?

**Comment by wjczf123** [comment]
I hope you can carefully check the results to ensure that the results can be reproduced.
